# Generated by Django 5.0.2 on 2024-02-21 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_profile_delete_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verification_code_created_at',
            field=models.DateTimeField(null=True),
        ),
    ]
